### PR TITLE
Feature/11997

### PR DESCRIPTION
**Pull request by gcutrini**
Realm integration on watchOS caused the weight of the distributed app to exceed the allowed 50mb.
This pull request reverts #23 and fixes integration with features introduced in #26.

### CODE REVIEW

**Comment by colemancda** [comment]
Well... all that work for nothing. I guess we need to migrate to CoreData asap.

**Comment by colemancda** [comment]
So I understand this reverts #23 (bummer) I dont understand exactly how this affects #26 ?

**Comment by gcutrini** [comment]
Yeah, I really appreciate the work on this and was sorry had to revert, but the included framework caused the watch app build to be above the 50mb limit. 
The fact that we had to revert gives us yet another reason to move off of Realm.

**Comment by colemancda** [comment]
That explains reverting #23, but how does this affect #26 ? Is that functionality still there?

**Comment by gcutrini** [comment]
The filtering introduced on #26 relied upon Realm.
Just needed to make some modifications to work without it.

Actually #26 solves much of hour memory issues since we are only listing filtered events.
Works great by the way.

**Comment by colemancda** [comment]
Great! So the app is usable without Realm and we have Event Filtering. This means the app shouldn't crash during the summit and we can work on CoreData integration after the Barcelona summit (which starts in 2 days).

**Pull request merged**
